# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # redox
  - board: nice_nano//zmk
    shield: redox_central_dongle dongle_display
    artifact-name: redox_central_dongle
  - board: nice_nano//zmk
    shield: redox_peripheral_left
    artifact-name: redox_peripheral_left
  - board: nice_nano//zmk
    shield: redox_peripheral_right
    artifact-name: redox_peripheral_right
  - board: nice_nano//zmk
    shield: settings_reset
  - board: nice_nano//zmk
    shield: redox_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_LOCKING=n
      -DCONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y
      -DCONFIG_ZMK_BEHAVIOR_LOCAL_IDS_IN_BINDINGS=y
      -DCONFIG_ZMK_FAST_KEYMAP=y
      -DCONFIG_ZMK_FAST_KEYMAP_STUDIO_RPC=y
      -DCONFIG_ZMK_FAST_KEYMAP_DEFAULT_LAYER=y
      -DCONFIG_ZMK_CUSTOM_SETTINGS=y
      -DCONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
      -DCONFIG_ZMK_CUSTOM_SETTINGS_STUDIO_RPC=y
      -DCONFIG_ZMK_RUNTIME_MACRO=y
      -DCONFIG_ZMK_RUNTIME_MACRO_STUDIO_RPC=y
      -DCONFIG_ZMK_RUNTIME_COMBO=y
      -DCONFIG_ZMK_RUNTIME_COMBO_STUDIO_RPC=y
      -DCONFIG_ZMK_BLE_MANAGEMENT=y
      -DCONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
      -DCONFIG_ZMK_DEFAULT_LAYER=y
      -DCONFIG_ZMK_DEFAULT_LAYER_STUDIO_RPC=y
      -DCONFIG_ZMK_OS_DETECTION=y
      -DCONFIG_ZMK_OS_DETECTION_USB=y
      -DCONFIG_ZMK_OS_DETECTION_BLE=y
      -DCONFIG_ZMK_OS_DETECTION_STUDIO_RPC=y
      -DCONFIG_ZMK_SETTINGS_RPC=y
      -DCONFIG_ZMK_SETTINGS_RPC_STUDIO=y
      -DCONFIG_ZMK_DEVICE_INFO=y
      -DCONFIG_ZMK_DEVICE_INFO_STUDIO_RPC=y
      -DCONFIG_ZMK_WATCHDOG=y
      -DCONFIG_ZMK_WATCHDOG_STUDIO_RPC=y
      -DCONFIG_ZMK_SPLIT_RELAY_EVENT=y
      -DCONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
      -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=768
      -DCONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=4096
      -DCONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=256
      -DCONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256
      -DCONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=256
      -DCONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
      -DCONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
      -DCONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6000
      -DCONFIG_ZMK_CUSTOM_SETTINGS_LARGE_VALUE_MAX_SIZE=256
      -DCONFIG_BT_L2CAP_TX_BUF_COUNT=15
      -DCONFIG_CONSOLE=n
      -DCONFIG_BOARD_SERIAL_BACKEND_CDC_ACM=n
    artifact-name: redox_central_dongle_studio