CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ---- DYA Studio split relay (peripheral side, no Studio RPC here) ----
CONFIG_ZMK_USB=n
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000